language: python

python:
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - "xvfb"

install:
  - "export DISPLAY=':99.0'"
  - "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"
  - "pip install stringify flake8"
  - "python setup.py install"

script:
  - "flake8 tk_tools"
  - "py.test tests/test_basic.py"
  - "py.test tests/test_LabelGrid.py"
  - "py.test tests/test_EntryGrid.py"
  - "py.test tests/test_ButtonGrid.py"
  - "py.test tests/test_KeyValueEntry.py"
